name: "build and deploy"

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        env:
          GH_TOKEN: ${{ secrets.DEPLOY }}
        run: |
          gh api \
            --method POST \
            /repos/Pratyay360/pratyay/dispatches \
            -f event_type=content_update